### ISSUE TITLE
Cant install requirements

### ISSUE THREAD

**Issue by 6Frauds** [dekrypted/simple-cookie-stealer#24]

**Comment by 6Frauds** [comment]
that code that your supposed to paste into terminal doesnnt work @dekrypted

**Comment by dekrypted** [comment]
ur hopeless

**Comment by 6Frauds** [comment]
loooool w customer service lmao

**Comment by dekrypted** [comment]
customer service? u didnt pay me aint no damn customer i dont wanna hear u complaining cause i wont help ur dumbass for free

**Comment by 6Frauds** [comment]
lol

**Comment by 6Frauds** [comment]
Its fine ion even need it anymore
